config/routes.rb
Intranet::Application.routes.draw do |map|

	match 'export', :to => 'employees#export'
	match 'employees/:id/profile' => 'employees#profile'
	match 'direct_deposit' => 'employees#direct_deposit'
	match 'personal_info' => 'employees#personal_info'
	match 'contact_info' => 'employees#contact_info'
	match 'search' => 'employees#search'
  resources :passwords, :employees, :articles

  match 'login', :to => 'application#login'
  match 'auth', :to => 'application#auth'
	match 'logout', :to => 'application#logout'

  
  match 'news', :to => 'articles#index'
  match 'policies', :to => 'pages#policies'

  root :to => "articles#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :passwords
	has_many :articles

	def self.authenticate(name, password)
    user = self.find(:first, "username = '#{name}' AND password = '#{password}'")
  end
  
  def self.search(q)
	  if q
	    find(:all, :conditions => ['name LIKE ?', "%#{q}%"])
	  else
	    find(:all)
	  end
	end
  
  ROLES = ['admin','hr','employee','blogger']
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	layout 'application'

	def index
    @employees = Employee.find(:all)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @employees }
    end
  end

  def create
    @employee = Employee.new(params[:employee])
    
    respond_to do |format|
      if @employee.save
        format.html { redirect_to(@employee, :notice => "Employee #{@employee.name} was successfully created.") }
        format.xml  { render :xml => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def show
    @employee = Employee.find(params[:id])
    @passwords = @employee.passwords
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @employee.to_xml(:include => :passwords) }
    end
  end
  
  def new
  	@employee = Employee.new
  	
  	respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @employee }
    end
  end
  
  def profile
  	@employee = Employee.find(params[:id])
  end
  
  def export
    send_file (Rails.root + params[:filename])
  end
  
  def direct_deposit
  	@employee = current_user
  end
  
  def personal_info
  	@employee= current_user
  end
  
  def contact_info
  	@employee = current_user
  end
  
  def search
  	@employees = Employee.search(params[:q])
  end
  
  def edit
    @employee = Employee.find(params[:id])
  end
  
  def update
    @employee = Employee.find(params[:id])
    
    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to(@employee, :notice => "#{@employee.name} successfully updated") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    
    respond_to do |format|
      format.html { redirect_to(employees_url) }
      format.xml  { head :ok }
    end
  end
  
  
	
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
    <ul>
    <% @employee.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
	<fieldset>
		<div class="form-group">
			<%= f.label :name %>
			<%= f.text_field :name, {:class => "form-control"} %>
		</div>
		
		<div class="form-group">
			<%= f.label :username %>
			<%= f.text_field :username, {:class => "form-control"} %>
		</div>
		
		<div class="form-group">
			<%= f.label :password %>
			<%= f.text_field :password, {:class => "form-control"} %>
		</div>
		
		<div class="form-group">
			<%= f.label :role %>
			<%= f.select :role, Employee::ROLES, {}, {:class => "form-control"} %>
		</div>
		
		<div class="checkbox">
			<%= f.label :active %>
			<%= f.check_box :active %>
		</div>
			
	</fieldset>
	
	<fieldset>
		<div class="form-group">
			<%= f.label :department %>
			<%= f.text_field :department, {:class => "form-control"} %>
		</div>
		
		<div class="form-group">
			<%= f.label "Social Security Number" %>
			<%= f.text_field :ssn, {:class => "form-control"} %>
		</div>
		
		<div class="form-group">
			<%= f.label :bank_account %>
			<%= f.text_field :bank_account, {:class => "form-control"} %>
		</div>
	</fieldset>
	

  <div class="actions">
    <%= f.submit "Submit", {:class => "btn btn-primary"} %>
    <%= link_to 'Back to Index', employees_path, {:class => "btn btn-default"} %>
  </div>
<% end %>

app/views/employees/contact_info.html.erb
<p class="notice"><%= flash[:notice] %></p>
<%= form_for(@employee, :remote => true) do |f| %>
	<div class="panel panel-info">
	  <!-- Default panel contents -->
	  <div class="panel-heading"><h3 class="panel-title">Contact info: <%= @employee.name %></h3></div>
	  <div class="panel-body">
	  	<div class="row">
				<div class="col-md-12">
					<fieldset>
						<div class="form-group">
							<%= f.label :email %>
							<%= f.text_field :email, {:class => "form-control"} %>
						</div>
						<div class="form-group">
							<%= f.label :im %>
							<%= f.text_field :im, {:class => "form-control"} %>
						</div>
					</fieldset>
				</div>
	  	</div>
	  	<div class="row">
	  		<div class="col-md-12">
		  		<%= f.submit "Submit", {:class => "btn btn-primary"} %>
	  		</div>
			</div>
	  </div>
	</div>
<% end %>

app/views/employees/direct_deposit.html.erb
<p class="notice"><%= flash[:notice] %></p>
<%= form_for(@employee, :remote => true) do |f| %>
	<div class="panel panel-info">
	  <!-- Default panel contents -->
	  <div class="panel-heading"><h3 class="panel-title">Direct deposit: <%= @employee.name %></h3></div>
	  <div class="panel-body">
	  	<div class="row">
				<div class="col-md-12">
					<fieldset>
						<div class="form-group">
							<%= f.label :ssn %>
							<%= f.text_field :ssn, {:class => "form-control"} %>
						</div>
						<div class="form-group">
							<%= f.label :bank_account %>
							<%= f.text_field :bank_account, {:class => "form-control"} %>
						</div>
					</fieldset>
				</div>
	  	</div>
	  	<div class="row">
	  		<div class="col-md-12">
		  		<%= f.submit "Submit", {:class => "btn btn-primary"} %>
	  		</div>
			</div>
	  </div>
	</div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<h1>Employees</h1>

<table class="table table-striped">
	<thead>
	  <tr>
	    <th>Name</th>
	    <th>Username</th>
	    <th>Active?</th>
	    <th>Department</th>
	    <th>Actions</th>
	  </tr>
	</thead>
	<tbody>
		<% @employees.each do |employee| %>
		  <tr>
		  	<td><%= link_to employee.name, employee_path(employee) %></td>
		  	<td><%= employee.username %></td>
		  	<td><%= employee.active %></td>
		  	<td><%= employee.department %></td>
		    <td>
		    	<% if @current_user.role == 'admin' || @current_user.role == 'hr' %>
						<%= link_to raw('<span class="glyphicon glyphicon-edit"></span>'), edit_employee_path(employee), {:class => 'btn btn-primary btn-xs'} %>
						<%= link_to raw('<span class="glyphicon glyphicon-trash"></span>'), employee, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger btn-xs' %>
					<% end %>
		    </td>
		  </tr>
		<% end %>
	</tbody>
</table>

<br />
<% if @current_user.role == 'admin' || @current_user.role == 'hr' %>
	<%= link_to raw('<span class="glyphicon glyphicon-plus"></span>'), new_employee_path, {:class => 'btn btn-success'} %>
<% end %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

app/views/employees/personal_info.html.erb
<p class="notice"><%= flash[:notice] %></p>
<%= form_for(@employee, :remote => true) do |f| %>
	<div class="panel panel-info">
	  <!-- Default panel contents -->
	  <div class="panel-heading"><h3 class="panel-title">Personal info: <%= @employee.name %></h3></div>
	  <div class="panel-body">
	  	<div class="row">
				<div class="col-md-12">
					<fieldset>
						<div class="form-group">
							<%= f.label :bio %>
							<%= f.text_area :bio, {:class => "form-control"} %>
						</div>
					</fieldset>
				</div>
	  	</div>
	  	<div class="row">
	  		<div class="col-md-12">
		  		<%= f.submit "Submit", {:class => "btn btn-primary"} %>
	  		</div>
			</div>
	  </div>
	</div>
<% end %>

app/views/employees/profile.html.erb
<p class="notice"><%= notice %></p>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Employee information</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-3">
                <img class="img-circle" src="/images/user100.png" alt="User Pic">
            </div>
            <div class="col-md-6">
                <strong><%= @employee.name %></strong><br>
                <table class="table table-condensed table-responsive table-user-information">
                    <tbody>
	                    <tr>
	                        <td>Department:</td>
	                        <td><%= @employee.department %></td>
	                    </tr>
	                    <tr>
	                        <td>Last update:</td>
	                        <td><%= l @employee.updated_at.localtime, :format => :short  %></td>
	                    </tr>
	                    <tr>
	                        <td>Role:</td>
	                        <td><%= @employee.role %></td>
	                    </tr>
	                    <tr>
	                        <td>Employee since:</td>
	                        <td><%= l @employee.created_at.localtime, :format => :short  %></td>
	                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <a href="mailto:<%= @employee.email %>" class="btn btn-sm btn-info"
                              data-toggle="tooltip"
                              data-original-title="Send email to employee"><i class="glyphicon glyphicon-envelope"></i></a>
        <span class="pull-right">
            <% if @current_user.role == 'admin' || @current_user.role == 'hr' %>
							<%= link_to raw('<span class="glyphicon glyphicon-edit"></span>'), edit_employee_path(@employee), {:class => 'btn btn-primary btn-sm'} %>
							<%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), @employee, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger btn-sm' %>
						<% end %>
        </span>
    </div>
</div><br>

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Employee bio</h3>
    </div>
    <div class="panel-body">
        <div class="row">
        	<div class="col-md-12">
        		<%= raw(@employee.bio) %>
        	</div>
        </div>
    </div>
    <div class="panel-footer">
        
    </div>
</div>

app/views/employees/search.html.erb
<div class="container">
 <div class="well col-sm-12 col-md-8 col-md-offset-2">
    <% @employees.each do |employee| %>
      <div class="row user-row">
          <div class="col-md-1">
              <img class="img-circle"
                   src="/images/user50.png"
                   alt="User Pic">
          </div>
          <div class="col-md-10">
              <strong><%= link_to employee.name, employee_path(employee) + '/profile' %></strong><br>
              <span class="text-muted">Department: <%= employee.department %></span>
          </div>
          <div class="col-md-1 dropdown-user" data-for="#<%= employee.username %>">
              <i class="glyphicon glyphicon-chevron-down text-muted"></i>
          </div>
      </div>
      <div class="row user-infos" id="<%= employee.username %>">
          <div class="col-sm-10 col-md-10 col-md-offset-1">
              <div class="panel panel-primary">
                  <div class="panel-heading">
                      <h3 class="panel-title">User information</h3>
                  </div>
                  <div class="panel-body">
                      <div class="row">
                          <div class="col-md-3">
                              <img class="img-circle"
                                   src="/images/user100.png"
                                   alt="User Pic">
                          </div>
                          <div class="col-md-6">
                              <strong><%= employee.name %></strong><br>
                              <table class="table table-condensed table-responsive table-user-information">
                                  <tbody>
	                                  <tr>
								                        <td>Last update:</td>
								                        <td><%= l employee.updated_at.localtime, :format => :short  %></td>
								                    </tr>
								                    <tr>
								                        <td>Role:</td>
								                        <td><%= employee.role %></td>
								                    </tr>
								                    <tr>
								                        <td>Employee since:</td>
								                        <td><%= l employee.created_at.localtime, :format => :short  %></td>
								                    </tr>
                                  </tbody>
                              </table>
                          </div>
                      </div>
                  </div>
                  <div class="panel-footer">
                      <a href="mailto:<%= employee.email %>" class="btn btn-sm btn-info"
                              data-toggle="tooltip"
                              data-original-title="Send email to employee"><i class="glyphicon glyphicon-envelope"></i></a>
                      <span class="pull-right">
                      	<% if @current_user.role == 'admin' || @current_user.role == 'hr' %>
													<%= link_to raw('<span class="glyphicon glyphicon-edit"></span>'), edit_employee_path(employee), {:class => 'btn btn-primary btn-sm'} %>
													<%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), employee, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger btn-sm' %>
												<% end %>
                      </span>
                  </div>
              </div>
          </div>
      </div>
		<% end %>
	</div>
</div>

app/views/employees/show.html.erb
<p class="notice"><%= notice %></p>
<div>
	<%= link_to 'Back', employees_path, {:class => 'btn'} %>
</div>
<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading"><h3 class="panel-title">Employee: <%= @employee.name %></h3></div>
  <div class="panel-body">
  	<div class="row">
  		<div class="col-md-12">
  			<% if @current_user.role == 'admin' || @current_user.role == 'hr' %>
	  			<%= link_to 'Edit', edit_employee_path(@employee), {:class => 'btn btn-default'} %>
	  		<% end %>
  		</div>
		</div>
  	<div class="row">
	  	<div class="col-md-4">
		    <dl class="dl-horizontal">
				  <dt>Username:</dt><dd><%= @employee.username %></dd>
				  <dt>Password:</dt><dd><%= @employee.password %></dd>
				  <dt>Role:</dt><dd><%= @employee.role %></dd>
				</dl>
	  	</div>
  		<div class="col-md-4">
		    <dl class="dl-horizontal">
				  <dt>Active:</dt><dd><%= @employee.active %></dd>
				  <dt>Department:</dt><dd><%= @employee.department %></dd>
				</dl>
			</div>
			<div class="col-md-4">
		    <dl class="dl-horizontal">
				  <dt>Social Security Number:</dt><dd><%= @employee.ssn %></dd>
				  <dt>Bank Account:</dt><dd><%= @employee.bank_account %></dd>
				</dl>
			</div>
  	</div>
  </div>

  <!-- Table -->
  <h4>Passwords</h4>
  <table class="table">
  	<thead>
  		<tr>
  			<th>Service</th>
  			<th>Username</th>
  			<th>Password</th>
  			<th>Shared</th>
  		</tr>
  	</thead>
  	<tbody>
    	<% @passwords.each do |pw| %>
    		<tr>
    			<td><%= pw.service %></td>
    			<td><%= pw.username %></td>
    			<td><%= pw.password %></td>
    			<td><%= pw.shared? ? 'yes' : 'no' %></td>
    		</tr>
			<% end %>
  	</tbody>
  </table>
</div>