config/routes.rb
Intranet::Application.routes.draw do |map|

	match 'export', :to => 'employees#export'
	match 'employees/:id/profile' => 'employees#profile'
	match 'direct_deposit' => 'employees#direct_deposit'
	match 'personal_info' => 'employees#personal_info'
	match 'contact_info' => 'employees#contact_info'
	match 'search' => 'employees#search'
  resources :passwords, :employees, :articles

  match 'login', :to => 'application#login'
  match 'auth', :to => 'application#auth'
	match 'logout', :to => 'application#logout'

  
  match 'news', :to => 'articles#index'
  match 'policies', :to => 'pages#policies'

  root :to => "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base

	belongs_to :author, :class_name => "Employee"
	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	layout 'application'
	
  # GET /articles
  # GET /articles.xml
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to(@article, :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(@article, :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(articles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  
  <fieldset>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, {:class => "form-control"} %>
		</div>
		
		<div class="form-group">
			<%= f.label :body %>
			<p class="help-block">Feel free to use HTML!</p>
			<%= f.text_area :body, {:class => "form-control"} %>
		</div>
		
		<div class="checkbox">
			<%= f.label :published %>
			<%= f.check_box :published %>
		</div>
		
		<%= f.hidden_field :author_id, :value => @current_user.id %>
			
	</fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Company News</h1>
<% if @current_user.role == 'blogger' || @current_user.role == 'admin' %>
	<%= link_to 'New Article', new_article_path %>
<% end %>
<div class="span8">
	<% @articles.each do |article| %>
    <h3><%= link_to article.title, article %></h3>
    <div class="body">
    	<%= raw(article.body) %>
    </div>
    <%= link_to 'Edit', edit_article_path(article) if article.author == @current_user %>
    <div>
        <span class="badge badge-success">Updated <%= l article.updated_at.localtime, :format => :short %></span>
        <div class="pull-right"><% if article.published? %><span class="label label-info">Published</span><% else %><span class="label label-warning">Unpublished</span><% end %> | <span class="glyphicon glyphicon-user"></span> <%= link_to article.author.name, employee_path(article.author) + '/profile' %></div>
    </div>
    <hr>
  <% end %>
 
</div>


<br />

app/views/articles/new.html.erb
<h1>New Company News Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p class="notice"><%= notice %></p>

<h1><%= @article.title %></h1>
	<div class="body">
  	<%= raw(@article.body) %>
  </div>
  <div>
  	<span class="badge badge-success">Updated <%= l @article.updated_at.localtime, :format => :short %></span>
    <div class="pull-right"><% if @article.published? %><span class="label label-info">Published</span><% else %><span class="label label-warning">Unpublished</span><% end %> | <span class="glyphicon glyphicon-user"></span> <%= link_to @article.author.name, @article.author %>
    </div>
  </div>
  <hr>